//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDiscount
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public double DiscountValue { get; set; }
        public int DiscountUnitId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public string CouponCode { get; set; }
        public double MinimumOrderValue { get; set; }
        public double MaximumDiscountAmount { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
    }
}
