//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrice
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public double BasePrice { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public short Status { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
    }
}
