//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDiscount()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string DiscountName { get; set; }
        public System.DateTime CreateDay { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidUtil { get; set; }
        public string CouponCode { get; set; }
        public double MinimumDiscountValue { get; set; }
        public double MaximumDiscountValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
