//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionDetail
    {
        public int Id { get; set; }
        public int PerId { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
    
        public virtual Permission Permission { get; set; }
    }
}
